# Generated by Django 2.2.20 on 2021-04-27 16:08

from django.db import migrations

MINIMAL_YEAR_VALUE_FOR_NEW_BUILDING = 2015


def set_is_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.new_building = (flat.construction_year >= MINIMAL_YEAR_VALUE_FOR_NEW_BUILDING)
        flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(set_is_new_building)
    ]
