# Generated by Django 2.2.20 on 2021-07-05 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20210503_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='owners_phonenumber',
            new_name='owner_phone_number',
        ),
    ]
