# Generated by Django 2.2.20 on 2021-07-06 14:59

from django.db import migrations


def move_owner_from_flat(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        new_owner, _ = Owner.objects.get_or_create(
            name=flat.owner,
            phone_number=flat.owner_phone_number,
            pure_phone=flat.owner_pure_phone,
        )
        new_owner.flats.add(flat)
        new_owner.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0013_owner'),
    ]

    operations = [
        migrations.RunPython(move_owner_from_flat)
    ]
